[tool.poetry]
authors = ["Dmitrii Orlov <dmtree.dev@yahoo.com>"]
description = ""
name = "chai_sql"
version = "0.1.0"

[tool.poetry.dependencies]
Arpeggio = "^2.0.0"
abnf = "^2.0.2"
click = "^8.1.3"
python = "^3.10"
sqlparse = "^0.4.3"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
isort = "^5.11.1"
mypy = "^0.991"
pytest = "^7.2.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = [
  "tests",
  "chai_sql",
]
